apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysa
---
apiVersion: v1
kind: Secret
metadata:
  name: mysa-secret
  annotations:
    kubernetes.io/service-account.name: mysa
type: kubernetes.io/service-account-token
