name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version: ^1.20
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Vet
      run: make vet

    - name: Fmt
      run: make fmt

    - name: Test
      run: go test -v ./...

    - name: Build
      run: GOCACHE=$(go env GOCACHE) make build


  linters:
    name: Run Linters
    runs-on: ubuntu-20.04

    steps:
    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version: ^1.20
      id: go

    - name: Set up Python 1.20
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        architecture: "x64"

    - name: Check out code
      uses: actions/checkout@v3

    - name: Python Linter
      run: make lint-python

    - name: Go Linter
      run: make lint-go


  acceptance-tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version: ^1.20
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: GOCACHE=$(go env GOCACHE) make build

    - name: Run Aceptance Tests
      run: |
        kind create cluster --name kid
        make test-acceptance-x
